Feature/sprint03 req04 products
paulocvasco/mercado-frescos-time-7 pull request #101
Opened 2022-07-05 19:21 UTC by rodney-martins

#80

2022-07-11 20:09 UTC, rodney-martins commented
```
INSERT INTO `mercado_fresco_db`.`countries`
(`country_name`)
VALUES
("Brasil");

INSERT INTO `mercado_fresco_db`.`provincies`
(`provincie_name`,
`id_country_fk`)
VALUES
("São Paulo",
1);


INSERT INTO `mercado_fresco_db`.`localities`
(`locality_name`,
`province_id`)
VALUES
("São Paulo",
1);

INSERT INTO `mercado_fresco_db`.`sellers`
(`cid`,
`company_name`,
`address`,
`telephone`,
`locality_id`)
VALUES
("abc",
"extra",
"av. paulista",
"0011223344",
1);

INSERT INTO `mercado_fresco_db`.`products_types`
(`description`)
VALUES
("frutas");

alter table products add constraint unique(product_code);

INSERT INTO `mercado_fresco_db`.`products`
(`id`,
`description`,
`expiration_rate`,
`freezing_rate`,
`height`,
`length`,
`net_weight`,
`product_code`,
`recommended_freezing_temperature`,
`width`,
`product_type_id`,
`seller_id`)
VALUES
(10,
"carambola",
2.1,
2.1,
2.1,
2.1,
2.1,
"teste",
2.1,
2.1,
1,
1);
```

2022-07-12 13:27 UTC, rodney-martins commented on go-web/internal/product_records/service.go
> +	Insert(record []byte) (models.ProductRecord, error)
Deixa eu checar

2022-07-12 13:50 UTC, rodney-martins commented on go-web/internal/product_records/service.go
> +	Insert(record []byte) (models.ProductRecord, error)
Cara vou checar isso depois, mas qq coisa faço o refactor p proxima sprint

2022-07-12 14:25 UTC, belmontejoao requested changes

2022-07-12 15:56 UTC, merged