`Wip` - Requesito  1 seller/testes
paulocvasco/mercado-frescos-time-7 pull request #61
Opened 2022-06-20 17:33 UTC by jandrade13

2022-06-27 15:24 UTC, belmontejoao requested changes

2022-06-27 15:24 UTC, belmontejoao commented on go-web/internal/Seller/service_test.go
> +		{"Get Id = 1", response[0], response[0], nil, "Id doesn`t exist", 1},
Acho que a mensagem deveria ser ao contrário

2022-06-27 15:24 UTC, belmontejoao commented on go-web/internal/Seller/service_test.go
> +		{"Update", response[0], response[0], valueUpdate[0], nil, "Errro Update", nil, nil},
Mesmo de cima

2022-06-28 15:48 UTC, jandrade13 commented on go-web/cmd/server/controller/seller_test.go
> +		}
```suggestion
	assert.Equal(t, value.expectResponse.data, res, value.message)
	assert.Equal(t, value.expectResponse.statusCode, w.Result().StatusCode, value.message)
		
```

2022-06-28 18:01 UTC, belmontejoao approved these changes

2022-06-28 18:02 UTC, merged